### ISSUE TITLE
Group Based Access Control (GBAC)

### ISSUE THREAD

**Issue by nOw-Ay** [ItalyPaleAle/traefik-forward-auth#11]
Hello there,

It's been two years since [the PR adding group support](https://github.com/thomseddon/traefik-forward-auth/pull/347) was submitted to thomseddon's repository. At this point, it's clear it’s never going to be merged.  

That’s why I was wondering if it might be possible to adapt the PR's changes to this project, even though it's now a hard fork.

As I mentioned in [this discussion](https://github.com/thomseddon/traefik-forward-auth/discussions/379), I’ll try to implement it myself—but since Go isn’t my language of choice, it might take some time.

Thanks a lot, and many thanks for maintaining this project! 👍🏻

**Comment by ItalyPaleAle** [comment]
Hi thanks for the suggestion.

Can you please elaborate a bit more on how you are thinking this should be implemented?

Where would the groups and group membership be stored? How would you configure it in TFA?

**Comment by nOw-Ay** [comment]
Sorry, the issue lacks context.

I believe the correct approach is to allow or deny the authentication request based on predefined rules. In ThomSeddon's project, for example, there's a single configuration file that defines the access rules. Here's an example:

```
rule.traefik.rule=Host(`traefik.internal.domain.org`)
rule.traefik.groups=Administrator
rule.portainer.rule=Host(`portainer.internal.domain.org`)
rule.portainer.groups=Administrator
```

In this project (please tell me if I'm wrong), it appears that everything is configured using environment variables or a YAML configuration file. After thinking it over, this might be a larger issue than I initially expected. It seems the project doesn't support granular access control for individual paths or applications, instead, it applies rules globally.

That's fine for most cases since you could theoretically define a new instance for each rule you want to apply, but it’s not practical. Would you be open to adding the ability to define custom rules for specific services and paths?

To help you understand how it could be implemented:

```
access_rules:
  - domain: "dasboards.internal.domain.org"
    rules:
      - group: "Administrator"
        paths:
          - "/admin"
          - "/dashboard"
      - group: "Manager"
        paths:
          - "/manager-dashboard"
          
  - domain: "portainer.internal.domain.org"
    rules:
      - group: "Administrator"
        paths:
          - "/settings"
          - "/containers"
      - group: "Viewer"
        paths:
          - "/logs"
```

From a technical point of view, I saw that part of this project codebase still looks very similar to thomseddon's project codebase, it should be compatible to a certain extent, the main difficulty is the difference in how rules are processed.

If you have any questions, don't hesitate to contact me 😃. I can't really promise anything but it would be a wonderful feature to have.

**Comment by ItalyPaleAle** [comment]
Thanks for providing the context.

I am open to adding support for some RBAC/GBAC, but I would like to get a bit more clarity on what is the underlying problem that users are trying to solve and how to best design a solution for it. To use an analogy, RBAC/GBAC are tools (like a drill), but I would like to get to the underlying problem that needs to be solved (getting a hole in the wall, to use the analogy), which I presume is authorizing certain users to do specific actions.

First, I want to clarify that this project is looking to solve the problem of _authentication_ (authn) and not _authorization_ (authz). Even the feature of Traefik this is meant to work with (Forward Auth) is [for authentication](https://doc.traefik.io/traefik/middlewares/http/forwardauth/), not authorization.

I am not sure I want to go down the path of implementing support for complex authz rules here, because first it will get very complex very quick (you already demonstrated domains and paths, next it will be path regexs, then headers, then...), and second because it would lead to authz rules being scattered in even more places.

Now, don't want to completely dismiss any improvement in this area. I think there are three areas that are worth exploring that may work for your problem too.

1. If all you want is to check whether a user can access a site, you could make sure that your OAuth2 app requires explicit user assignment.
   - For example, say you are using Microsoft Entra ID, you can restrict the app (service principal) to users that are explicitly assigned too, either directly or through a group. This is already doable with TFA today.
2. I am open to the idea of adding simple rules to TFA such as enforcing that a claim is present in the token issued by the IdP.   - TFA already support some naive rules such as allowlisting user IDs or emails ([see Google example](https://github.com/ItalyPaleAle/traefik-forward-auth/blob/main/docs/04-authentication-providers.md#google))
      - _As a PS, I don't love that there's allowlists in TFA today for users/emails, as I really think that authz decisions should be kept out of this project, but this was simple enough, arguably had enough demand for it, and was already possible with thomseddon's project_).
    - Adding a rule to enforce that a specific claim is present with a specific value (e.g. checking the `groups` claim containing a certain value) is something I'm open to.
    - If you want to have per-domain or per-path rules, the current approach requires running multiple instances of TFA, and define multiple Forward Auth middlewares in Traefik, and then defining in the Traefik's config which routers use which forward auth middlewares.
3. While point 2 is totally valid, and can already be done today, I admit it does add quite a bit of complexity, having to manage many instances of TFA...
   - For that, I want to introduce what I've been working on for TFA v4, which is [currently in development](https://github.com/ItalyPaleAle/traefik-forward-auth/tree/v4-devel) (design isn't final). I'm introducing the concepts of "portals", which allow defining multiple configurations in the same TFA process.
   - The idea is that each "portal" has its own set of IdPs supported (so you can have 3 portals: one which offers Google with app A, one that offers Google with app B, and one that offers Tailscale or MS Entra ID). Each portal also allows configuring allowlists for users, and I could add support for reading specific claims, as in point 1 above

Sorry for the wall of text. Let me know if you have any thoughts.

**Comment by ItalyPaleAle** [comment]
> Your idea of "portals" is very interesting. I'm looking forward to seeing it in action. I just have one question: where would we define which requests get routed to which portal? Would we use multiple middlewares for different portals, or a single middleware configured via an internal config file?

Let me start from here. It's implemented already but I have to clean up a few things and write docs. At a high level, think of portals as a way to run multiple instances of TFA v3, each with its own IdP configured (bonus: they are now "lists of IdPs", so you can offer more than one choice), but without having to manage multiple replicas of the process/container, each with its own config.

```yaml
portals:
  - name: github-only
    displayName: "GitHub Authentication"
    providers:
      - provider: github
        config:
          clientID: "your-client-id"
          clientSecret: "your-client-secret"
          allowedUsers: ["githubuser1" ,"githubuser2"]
  - name: mix-portal
    displayName: "Google and MS Entra ID"
    providers:
      - provider: google
        config:
          clientID: "your-google-client-id.apps.googleusercontent.com"
          clientSecret: "your-client-secret"
          allowedUsers: ["user1" ,"user2"]
          allowedEmails: ["user@example.com"]
          allowedDomains: ["yourdomain.com"]
      - provider: microsoftentraid
        config:
          tenantID: "your-tenant-id"
          clientID: "your-client-id"
          clientSecret: "your-client-secret"
          allowedUsers: ["user-object-id"]
          allowedEmails: ["user@example.com"]
```

Each portal has its own endpoint, for example (assuming TFA is listening on `http://localhost:4181`) `http://localhost:4181/portal/github-only` and `http://localhost:4181/portal/mix-portal`

You can then configure Traefik with **multiple** Forward-Auth middlewares, for example (example Traefik dynamic config as YAML): 

```yaml
http:
  middlewares:
    forwardAuth:
      forwardauthGitHub:
        address: "http://localhost:4181/portal/github-only"
        authResponseHeaders: ["X-Forwarded-User"]
        trustForwardHeader: true
      forwardauthMix:
        address: "http://localhost:4181/portal/mix-portal"
        authResponseHeaders: ["X-Forwarded-User"]
        trustForwardHeader: true
```

Then you can configure your routers in Traefik using `forwardauthGitHub` or `forwardauthMix` middlewares.

> I understand your view that authorization decisions shouldn't be handled within an authentication middleware. Is your hesitation mainly because of your interest in implementing a cleaner solution elsewhere, or do you think handling authorization in the same middleware would introduce unnecessary complexity? Do you believe a separate middleware would be a better approach?

My main hesitation is the complexity it would introduce. In your example above you showed defining rules per-domain and per-path. A fast-follow request would be defining rules per path regex, and then based on Auth headers. And then people would want rules based ....

At that point, it feels like there'd be a lot of complexity in TFA and it's partly a duplicate of what Traefik does. In fact, Traefik already allows defining routers based on a domain, a path, a path regex, and other things.

So my preference would be to keep the definition of all authz rules outside of the config for TFA, and maybe in the Traefik's config. This seems a more appropriate place because:

1. Traefik already has a very powerful engine to create routers based on many aspects of the request
2. This allows keeping more of the config in the same place, rather than having yet another file where business logic (AuthZ) is placed

For example, the example you showed above could be converted to a Traefik config that uses 2 routers and each one using a different Forward Auth middleware:

```yaml
http:
  routers:
    dashboardAdmin:
      entryPoints: ["http"]
      middlewares:
        - "forwardAuthAdmin"
      rule: "Host(`dasboards.internal.domain.org`) && (PathPrefix(`/admin`) || PathPrefix(`/dashboard`))"
      service: dashboard
    dashboardManager:
      entryPoints: ["http"]
      middlewares:
        - "forwardAuthManager"
      rule: "Host(`dasboards.internal.domain.org`) && PathPrefix(`/manager-dashboard`)"
      service: dashboard
```

This gives you the ability to use all of the Traefik's rule engine (which is quite powerful) and you don't need to define AuthZ logic in another service's (TFA) configuration.

Do you think this could work for your use case?

Now, going back to what I said yesterday a bit, I actually realized that defining a different portal for various RBAC rules (e.g. one portal uses Google auth and requires no claims, and another uses Google auth and requires the "admin" claim in the groups) wouldn't work. The reason is that each portal in TFA v4 has its own session cookie, and sharing them across portals wouldn't work.

But what I could do is add the option to enforce the presence of claims via query string args. For example, you'd be able to define your Traefik middlewares such as:

```yaml
http:
  middlewares:
    forwardAuth:
      forwardauthAdmin:
        address: "http://localhost:4181/portal/google?rbac=group:admin"
        authResponseHeaders: ["X-Forwarded-User"]
        trustForwardHeader: true
      forwardauthManager:
        address: "http://localhost:4181/portal/google?rbac=group:manager"
        authResponseHeaders: ["X-Forwarded-User"]
        trustForwardHeader: true
```

(Design isn't final, especially for the query string args names :) )

**Comment by ItalyPaleAle** [comment]
I've given this more thought and I think I do like the approach I hinted at in my last comment.

To recap:

1. To the endpoint that checks whether a user is authenticated, we will add the option to additionally check if a claim is present. This is done via query string args.
   - `?if=key%3Dvalue` (`%3D` is `=`) checks if the token contains the claim `key` with value `value`.
      - Example: to enforce that a token has the claim `{"role":"admin"}`, you'd set `?if=role%3Dadmin`
   - `?if=array%25value` (`%25` is `%`) checks if the token contains the claim `array` which contains `value`. For compatibility, if the claim's value is a string, it's assumed to be an array with 1 value.
      - Example: `?if=group%25manager` would require the token to have `{"group": ["manager"]}`, and would accept `{"group":"manager"}` too
   - If a check fails, the endpoint responds with 403 (Forbidden).
   - You can only pass one `?if` argument. Keep it simple :)
2. The actual AuthZ decisions are made in the Traefik's dynamic configuration, where you can define multiple Forward Auth middlewares with the query string args above:

   ```yaml
   http:
     middlewares:
       forwardAuth:
         forwardauthAdmin:
           address: "http://localhost:4181/portal/google?if=group%25admin"
           authResponseHeaders: ["X-Forwarded-User"]
           trustForwardHeader: true
         forwardauthManager:
           address: "http://localhost:4181/portal/google?if=group%25manager"
           authResponseHeaders: ["X-Forwarded-User"]
           trustForwardHeader: true
   ```

Benefits:

- Allows both RBAC and GBAC with a design that's flexible to accomodate any kind of checks on claims (also for tokens that use different names for the claims)
- Should be on the simpler end, to implement/maintain and to use.
- Does not require implementing business logic (authz rules) in the TFA's configuration. That will stay in the Traefik's configuration (which can be set via labels on container)

What do you think? Would this work for you?
