### ISSUE TITLE
Keeps redirecting with generic openidconnect provider

### ISSUE THREAD

**Issue by TomBillietKlarrio** [ItalyPaleAle/traefik-forward-auth#15]
Hi,

I'm trying out this for as an alternative for the original traefik-fwd-auth implementation. It seems I can't get it working though, and do no see how it can ever work.
If I look at:
https://github.com/ItalyPaleAle/traefik-forward-auth/blob/78a1fa05ff578ced2a4d3b4279122d2603c714e9/pkg/server/server.go#L184
-> it has a sepearate route for the callback url.
However, traefik-forward-auth (https://doc.traefik.io/traefik/middlewares/http/forwardauth) sends everything to the same route (`/auth`) in my case, and the `X-Forwarded-Uri` parameter should be used to determine the actual route. I don't see this happening, so the authentication starts again when the callback url is hit.

Any clue what I'm doing wrong?

Thanks,
Tom

**Comment by TomBillietKlarrio** [comment]
I assume you can get it working, I just seem to miss how :-) 

My guess is it could be related with using `dedicated sub-domain` vs `using a sub-path`. I'm trying the latter. The dedicated sub-domain would probably work.

So my config:
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: test-forward-auth
  namespace: tom
spec:
  forwardAuth:
    address: http://test-forward-auth.tom.svc.cluster.local:4181/auth
    trustForwardHeader: true
```

And TFA itself:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-forward-auth
  namespace: tom
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-forward-auth
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-forward-auth
      name: test-forward-auth
    spec:
      containers:
      - env:
        - name: TFA_HOSTNAME
          value: "my-app.test.com"
        - name: TFA_BASEPATH
          value: "/auth"
        - name: TFA_LOGLEVEL
          value: "debug"
        - name: TFA_LOGSASJSON
          value: "false"
        - name: TFA_METRICSSERVERENABLED
          value: "true"
        - name: TFA_AUTHPROVIDER
          value: "openidconnect"
        - name: TFA_AUTHOPENIDCONNECT_CLIENTID
          value: "test"
        - name: TFA_AUTHOPENIDCONNECT_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              key: attribute.client_secret
              name: test-forward-auth-client
              optional: false
        - name: TFA_TOKENSIGNINGKEY
          valueFrom:
            secretKeyRef:
              key: signing_key
              name: test-forward-auth-signing
              optional: false
        - name: TFA_AUTHOPENIDCONNECT_TOKENISSUER
          value: "https://auth-server.test.com/"
        - name: TFA_AUTHOPENIDCONNECT_ENABLEPKCE
          value: "true"
        image: 
        imagePullPolicy: Always
        name: test
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 64Mi
        securityContext:
          capabilities:
            drop:
            - all
```
This configuration worked nicely with the thomseddon/traefik-forward-auth, but I'm looking at replacing it.

It starts nicely, if you navigate to the app, TFA will intercept the request and start the login. The login succeeds at the IDP, and send it back to the same app url, on the path `/auth/oauth2/callback`.
And this is where it fails, Traefik will call the TFA middleware on `/auth`, putting `/auth/oauth2/callback` as the `X-Forwarded-Uri` header. And hence TFA will not treat this as a callback call, but just start the authentication again.

**Comment by ItalyPaleAle** [comment]
Thanks, I use the path-based method in my dev environment. What I found is that these authentication loops could be caused by incorrectly configuring the route in Traefik.

The `Deployment` and `Middleware` you've shared look correct.

Could you please also share the `Service` and `IngressRoute` resources you've configured in your cluster? (if not using the CR, then the `Ingress` resource) Both for your app and for TFA.

Assuming you have a `Service` called `test-forward-auth`, the `IngressRoute` for TFA should look something like this:

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: test-forward-auth
  namespace: tom
spec:
  entryPoints:
    - "websecure"
  routes:
    - kind: "Rule"
      match: "Host(`my-app.test.com`) && PathPrefix(`/auth`)"
      services:
        - kind: Service
          name: traefik-forward-auth
          namespace: tom
          passHostHeader: true
          port: 4181
          scheme: http
```

Things to note:

1. Route should match the Host and PathPrefix
1. IMPORTANT: Do NOT add the forward-auth middleware to this IngressRoute

**Comment by TomBillietKlarrio** [comment]
I see. My ingress and service are:
```
apiVersion: v1
kind: Service
metadata:
  name: test-forward-auth
  namespace: tom
spec:
  ports:
  - name: traefik-forward-auth
    port: 4181
    protocol: TCP
    targetPort: 4181
  selector:
    app.kubernetes.io/name: test-forward-auth
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-https-redirect-permanent@kubernetescrd,traefik-hsts-headers@kubernetescrd,tom-tom-fwd-auth-test-forward-auth@kubernetescrd
  name: whoami
  namespace: tom
spec:
  ingressClassName: traefik
  rules:
  - host: my-app.test.com
    http:
      paths:
      - backend:
          service:
            name: my-app
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - my-app.test.com
    secretName: tom-cert
```

So if I understand this correctly, I should add a different path to the ingress for `/auth/oauth2/callback` that sends this path directly to the TFA service, and not to my own service? That could explain the behavior, but is different from the original traefik-forward-auth. So that could explain my confusion.
I can't test it right now, but will come back with my result.

Big thanks for your help already!

**Comment by mouse256** [comment]
I see, I missed that part in the docs. I'll try it.
btw: any specific reason why you deviated with this behavior from the thomseddon project? To me it looks like that's easier to configure, there is no special route in the ingress needed. Would that be an option you'd consider adding?

**Comment by TomBillietKlarrio** [comment]
I can confirm it works indeed like that!
However I could not get it working with a regular `ingress` object. As you should create 2 different ingress objects, and ignore the callback path from 1 of them. Which I think is not supported by default in k8s. It works when using an `ingressroute` traefik object.
So would it be an option to add this feature? Or would you be willing to incorporate it if we would contribute it?

**Comment by ItalyPaleAle** [comment]
> I can confirm it works indeed like that!
> However I could not get it working with a regular `ingress` object. As you should create 2 different ingress objects, and ignore the callback path from 1 of them. Which I think is not supported by default in k8s. It works when using an `ingressroute` traefik object.
> So would it be an option to add this feature? Or would you be willing to incorporate it if we would contribute it?

Could you share an example of what you tried with a regular `ingress`? I'm not sure I understand the issue and why you needed two. (I also don't have a lot of experience with regular Ingress resources as I've pretty much always used the traefik's CRD)

**Comment by TomBillietKlarrio** [comment]
Sure: I have this service:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-https-redirect-permanent@kubernetescrd,traefik-hsts-headers@kubernetescrd,tom-tom-fwd-auth-test-forward-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.pathmatcher: PathRegexp
  name: whoami
  namespace: tom
spec:
  ingressClassName: traefik
  rules:
  - host: my-app.test.com
    http:
      paths:
      - backend:
          service:
            name: whoami
            port:
              number: 8080
        path: "/"
        pathType: Prefix
  tls:
  - hosts:
    - my-app.test.com
    secretName: tom-test
```

The issues are
* The middlewares are configured on annotation level of the ingress. So it's all or nothing. You can't indicate to use middleware X for route A and user middleware Y for route B. So that's why you would need to different ingresses.
* But AFAIK you can only do positive matching. So on the `Path` I don't think there is a possibility to indicate: "match pathprefix `/`, but do not match the patch `/auth/oauth2/callback`. So adding a 2nd ingress that would listen for that path would start confusing call, they might end up by either service that matches.
