### ISSUE TITLE
Redirect back to the origin host

### ISSUE THREAD

**Issue by iberflow** [ItalyPaleAle/traefik-forward-auth#7]
Hi, thank you for this project. I've integrated a self hosted logto.io instance to secure some services, but the only thing that I can't figure out is how to redirect the user back to the origin address. Seems like this project doesn't handle that, instead it prints "You're authenticated as" message. It's not really a big issue, but it would improve UX if we could redirect back to the forwardauth middleware protected service.

Initially I was thinking it could be achieved by setting a temporary cookie containing the url/hostname of the secured service which can get overwritten/deleted on consecutive calls or successful authentication, but having given it a bit of thought I understand that this is not possible due to how the initial request is done by Traefik and not the browser. Maybe some sort of fingerprinting and/or a combination of forwardauth request headers/url params could work?

I understand this is a low priority problem, but If you get a chance to share your thoughts and it seems like it's doable, I'd love to contribute.

Many thanks,
Ignas

**Comment by ItalyPaleAle** [comment]
Hi @iberflow could you share some details on your setup?

Normally, the user should never see the "You're authenticated as" page from traefik-forward-auth, because the users should never hit TFA except for the OAuth2 redirect.

**Comment by alexbaeza** [comment]
Hey all, 

I'd like to chip in to the discussion as I've seen this sort of auth issues in the past, this is usually due to a miss configuration on the `redirect_url` it's a very common problem. 

Assuming that your `traefik-forward-auth` instance is hosted in `auth.yourdomain.com`

You need to ensure the redirect url in `logto.io` is set to `auth.yourdomain.com/oauth2/callback` and not `auth.yourdomain.com`. 

I think that would explain why you're being redirected to the main page. Which outputs the "You're authenticated as"

Some debugging steps you could do is check the `logto.io` url you're being redirected to: it should have something like:

```
https://logto.io&redirect_uri=https%3A%2F%2Fauth.yourdomain.com%2Foauth2%2Fcallback&response_type=code&scope=openid%20profile%20emai
```
Double check the redirect_uri query param :) 

Thanks

**Comment by iberflow** [comment]
Hmm, that's how the redirect_uri is setup on my end, but I may be missing something.
<img width="328" alt="Image" src="https://github.com/user-attachments/assets/06144a6b-1dc0-4950-848b-9a0750a43724" />

My setup is this:

auth.example.com -> logto instance
to.auth.example.com -> traefik-forward-auth
traefik.auth.example.com -> traefik's dashboard with forwardauth middleware
a.auth.example.com -> (soon) other web dashboard with forwardauth middleware
b.auth.example.com -> (soon) other web dashboard with forwardauth middleware


traefik_dynamic.yaml (unrelated issue, but for some reason I can't get this to work with docker labels on the traefik container, therefore the config file)

```
http:
  routers:
    api:
      rule: 'Host(`traefik.auth.example.com`)'
      entrypoints:
        - websecure
      service: api@internal
      middlewares:
        - logto-forwardauth
      tls:
        certResolver: example
  middlewares:
    logto-forwardauth:
      forwardauth:
        address: "https://to.auth.example.com"
        trustForwardHeader: "true"
        authResponseHeaders:
          - "X-Forwarded-User"
```

traefik-forward-auth env:
```
TFA_AUTHPROVIDER=openidconnect
TFA_AUTHOPENIDCONNECT_CLIENTID=xxxx
TFA_AUTHOPENIDCONNECT_CLIENTSECRET=xxxx
TFA_AUTHOPENIDCONNECT_TOKENISSUER=https://auth.example.com/oidc
TFA_LOGLEVEL=debug",
TFA_HOSTNAME=to.auth.toawe.me
TFA_COOKIEDOMAIN=toawe.me
```

The issue is only for the 1st login, once the user is authenticated he then stays on the origin host.
